[package]
authors = ["Jason Leonhard <leonhard.jason@gmail.com>"]
edition = "2018"
name = "get_request"
version = "0.1.0"

[dependencies]
hyper = "0.13"
pretty_env_logger = "0.4.0"
reqwest = {version = "0.10", features = ["json"]}
tokio = {version = "0.2", features = ["full"]}
